### ISSUE TITLE
UI needs improvement 

### ISSUE THREAD

**Issue by EyuCoder** [elysium09/MVVM_Notes#7]
The UI design needs some touch up

**Comment by Akash82228** [comment]
sir i want to contribute to this Repository i have fair experience of android development in kotlin.

**Comment by elysium09** [comment]
Hello Akash, I am glad to hear you're interested in the project. what
specifically do you want to work on? that issue #7 is a bit generalized so
selected some specific functionality or improvements you'd like to add to
the app and let me know. after that we can create issues and i will assign
you there on github.
